aitomaton_config:
  total_cards: 15 # Overridden if pack_builder is enabled
  concurrency: 15
  image_mode: "random" # options: custom, dall-e-2, dall-e-3, localSD, none

tts_export:
  cleanup: false
  copy_to_savedobj: true

set_params:
  set: "Merlins Menagerie"
  themes:
    - "Huge Deck Size"
    - "Self Milling"
    - "Graveyard Recursion"
    - "Library"
    - "Collector"
    - "Hoarding"
    - "Card Draw Payoff"
    - "Deck Manipulation"
    - "Collection Synergy"
    - "Threshold Effects"
    - "Deck Size Matters"
    - "Archive"
    - "Merlins Fantastic Beasts"
    - "Old wizard"

skeleton_params:
  types_mode: play
  power_level: 10
  standard_deviation_powerLevel: 0.5
  power_level_rarity_skew: 0.2
  function_tags:
    ramp or mana fixing: 15
    draw or card advantage: 15
    removal or control: 10
    board wipe or mass removal: 5
    activated ability: 5
    Flying or other evasion: 5
    simple or straightforward: 10
    graveyard recursion: 15
    self mill: 15
    deck size matters: 15
    collection synergy: 15
    archive manipulation: 15
  tags_maximum: 3 # Default is null, which means no limit
  fixed_amount_themes: 1 # if not zero, will select a fixed amount of themes from the available ones instead of mutating them randomly
  mutation_chance_per_theme: 11 # Chance to mutate each theme, ignored if fixed_amount_themes is not zero