aitomaton_config:
  total_cards: 60 # Overridden if pack_builder is enabled
  concurrency: 15
  image_mode: "none"

skeleton_params:
  power_level: 10
  standard_deviation_powerLevel: 0.5
  power_level_rarity_skew: 0.2

pack_builder:
  enabled: true