square_config:
  total_cards: 60 # Overridden if pack_builder is enabled
  concurrency: 1

skeleton_params:
  power_level: 10
  standard_deviation_powerLevel: 0.5
  power_level_rarity_skew: 0.2

pack_builder:
  enabled: true

api_params:
  image_model: "none" # options: dall-e-2, dall-e-3, none